---
# Source: postgrescluster/templates/pgbackrest-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: qa1-pgbackrest-secret
type: Opaque
data:
  azure.conf: |-
        CltnbG9iYWxdCnJlcG8xLWF6dXJlLWFjY291bnQ9MzI0MGZmMzczZGZlNWJmMTkwNzcwNTQxCnJlcG8xLWF6dXJlLWtleT10NjB3SzJtbk8rc3dtMTdVZFVVNEQzbklhZEpsY0s1TFdOejlOU2o3S2t0dmNzNmFXMXJXRmNjdXhwU1hSNW9pTkpDOWpXeU0vZmJ3K0FTdFQ4UmhDdz09
---
# Source: postgrescluster/templates/postgres.yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: qa1
spec:
  postgresVersion: 13
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-13.9-0
  instances:
    - name: "instance1"
      replicas: 1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"
      resources:
        limits:
          memory: "1Gi"
  backups:
    pgbackrest:
      configuration:
      - secret:
          name: qa1-pgbackrest-secret
      global:
        repo1-path: /pgbackrest/default/qa1/repo1
      repos:
      - name: repo1
        azure:
          container: "crunchy-backup"
  proxy:
    pgBouncer:
      replicas: 1
  userInterface:
    pgAdmin:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgadmin4:ubi8-4.30-0
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
