---
# Source: postgrescluster/templates/pgbackrest-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: qa3-pgbackrest-secret
type: Opaque
data:
  azure.conf: |-
        CltnbG9iYWxdCnJlcG8xLWF6dXJlLWFjY291bnQ9ODhmZDNmYjJiOGQ2NWExMmI3MGQ5NjcyCnJlcG8xLWF6dXJlLWtleT01T1F5RFM5ZHZKNmZxb0U0MFY5OWg4YmdQd0tIdkpCZFE5WGNyd0dCdWZNWm1Zb2RUVUJVZ2h1TlNrT0pWSWVCd214dCtxUFVBbVlLK0FTdGVkQy9EUT09
---
# Source: postgrescluster/templates/postgres.yaml
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: qa3
spec:
  postgresVersion: 13
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-13.9-0
  instances:
    - name: "instance1"
      replicas: 1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"
      resources:
        limits:
          memory: "1Gi"
  backups:
    pgbackrest:
      metadata:
        labels:
          sidecar.istio.io/inject: 'false'
      configuration:
      - secret:
          name: qa3-pgbackrest-secret
      global:
        repo1-path: /pgbackrest/default/qa3/repo1
      repos:
      - name: repo1
        azure:
          container: "crunchy-backup"
      manual:
        repoName: repo1
        options:
         - --type=full
  proxy:
    pgBouncer:
      replicas: 1
      config:
        global:
           query_wait_timeout: "240" 
           default_pool_size: "100"
           max_client_conn: "1000" #change depending on your app requirement  
           # I could not get the "datbases:" setting to work at all.  I have no idea what is wrong with it.
           # https://access.crunchydata.com/documentation/postgres-operator/5.0.0/tutorial/connection-pooling/
           # https://www.pgbouncer.org/config.html
  users:
  - name: lti-qa3  # this user is allowed through pg-bouncer
    databases:
      - qa3
      #- keycloak
      #- camunda
      #- postgres
    options: 'SUPERUSER'
  - name: lti-admin  # not allowed through pg-bouncer (SUPER USER)
    databases:
      - qa3
      #- keycloak
      #- camunda
      #- postgres
    options: 'SUPERUSER'
  userInterface:
    pgAdmin:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgadmin4:ubi8-4.30-0
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
